<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>repository</artifactId>
        <groupId>izotov.kern.iam</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>repository.mirgation</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-jdbc</artifactId>
            <version>4.0.5</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.8</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- LIQUIBASE -->
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>${liquibase.version}</version>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>7.0.2</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>${dmp.version}</version>
                <executions>
                    <!-- Старт БД в докере для накатывания скриптов и генерации кода во время сборки проекта -->
                    <execution>
                        <id>postgres-start</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <images>
                                <image>
                                    <name>postgres:17</name>
                                    <alias>${postgres.alias}</alias>
                                    <run>
                                        <containerNamePattern>${postgres.alias}-build</containerNamePattern>
                                        <env>
                                            <POSTGRES_USER>${postgres.user}</POSTGRES_USER>
                                            <POSTGRES_PASSWORD>${postgres.password}</POSTGRES_PASSWORD>
                                            <POSTGRES_DB>${postgres.db}</POSTGRES_DB>
                                        </env>
                                        <ports>
                                            <port>5433:5432</port>
                                        </ports>
                                        <wait>
                                            <log>database system is ready to accept connections</log>
                                            <time>10000</time>
                                        </wait>
                                    </run>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                    <!-- Остановка докер контейнера с БД после сборки модуля repository -->
                    <execution>
                        <id>postgres-stop</id>
                        <phase>install</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase.version}</version>
                <executions>
                    <!-- Применение liquibase скриптов -->
                    <execution>
                        <id>liquibase-update</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>update</goal>
                        </goals>
                        <configuration>
                            <url>jdbc:postgresql://localhost:5433/${postgres.db}</url>
                            <username>${postgres.user}</username>
                            <password>${postgres.password}</password>
                            <driver>org.postgresql.Driver</driver>
                            <changeLogFile>src/main/resources/scripts/master.yml</changeLogFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>